name: Docker Containers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build
